// vue/src/components/EditTask.vue
<template>
  <div
    class="modal fade"
    id="staticBackdrop"
    data-bs-backdrop="static"
    data-bs-keyboard="false"
    tabindex="-1"
    aria-hidden="true"
    ref="dialog"
  >
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Edit Task</h5>
          <button
            type="button"
            class="btn-close"
            @click="cancel"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <div>
            <label for="title" class="form-label">Title</label>
            <input class="form-control" type="text" id="title" v-model="task.title" />
          </div>
          <div>
            <label for="description" class="form-label">Description</label>
            <textarea
              class="form-control"
              type="text"
              id="description"
              v-model="task.description"
            />
          </div>
        </div>
        <div class="modal-footer">
          <button class="btn btn-primary" @click="updateTask">Update</button>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import { Modal } from "bootstrap/dist/js/bootstrap.esm.min.js";

export default {
  name: "EditTask",
  data() {
    return {
      task: {
        title: "",
        description: "",
      },
      modal: null,
    };
  },
  methods: {
    cancel() {
      this.modal.hide();
    },
    edit(task) {
      this.task = task;
      this.modal.show();
    },
    updateTask() {
      this.modal.hide();
      this.$store.dispatch("updateTask", {
        ...this.task,
      });
    },
  },
  mounted() {
    console.log(this.$refs.dialog);
    this.modal = new Modal(this.$refs.dialog);
  },
};
</script>

<style>
.form-label {
  display: block;
  text-align: left;
  margin-top: 1rem;
  padding-left: 0.5rem;
}

input {
  width: 100%;
}
</style>

// react/src/EditTask.js
import { Button, Form, Label, Modal } from 'react-bootstrap';
import { useEffect, useState } from 'react';

function EditTask(props) {

    const [show, setShow] = useState(props.task);
    const [task, setTask] = useState(props.task);

    function handleClose() {
        console.log('handleClose');
        setShow(false);
    }

    function handleChange(event) {
        console.log('handleChange: %s %s', event.target.name, event.target.value);
        setTask({ ...task, [event.target.name]: event.target.value });
    }

    function save(event) {
        console.log('save: %o', task);
        event.preventDefault();
        props.onSave(task);
        setShow(false);
    }

    let dialog = null;

    useEffect(() => {
        setShow(props.task);
        setTask(props.task);
    }, [props.task]);

    if (task) {
        console.log('props.task: title=%s', task.title);
        dialog = (
            <Modal.Dialog>
                <Modal.Header closeButton="true">
                    <Modal.Title>Edit Task</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <Form>
                        <Form.Group>
                            <Form.Label>Task Name</Form.Label>
                            <Form.Control type="text" placeholder="Enter Task Name" name="title" value={task.title} onChange={handleChange} />
                        </Form.Group>
                        <Form.Group>
                            <Form.Label>Task Name</Form.Label>
                            <Form.Control type="text" placeholder="Enter Task Description" name="description" value={task.description} onChange={handleChange} />
                        </Form.Group>
                    </Form>
                </Modal.Body>
                <Modal.Footer>
                    <Button variant="primary" type="submit" onClick={save}>
                        Save Changes
                    </Button>
                </Modal.Footer>
            </Modal.Dialog>
        );
    }

    return (

        <Modal show={show}
            onHide={handleClose}
            backdrop="static">
            {dialog}
        </Modal>)



}

export default EditTask;
