// react/src/Lanes.js
import { Button, Card, Row } from 'react-bootstrap';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import './Lanes.css';

function Lanes(props) {

    function addTask(ev) {
        console.log("addTask: %o", ev)
    }

    function edit(task, ev) {
        console.log("edit: %o %o", ev, task)
        props.editTask(task);
    }


    function dragStart(event) {
        event.dataTransfer.dropEffect = "move";
        event.dataTransfer.setData("text/plain", event.target.dataset.id);
        event.currentTarget.classList.add("drag");
    }

    function dragEnd(event) {
        event.currentTarget.classList.remove("drag");
    }

    function dragOver(event) {
        event.preventDefault();
        event.dataTransfer.dropEffect = "move";
    }

    function drop(event) {
        event.preventDefault();
        let taskId = event.dataTransfer.getData("text/plain");

        if (event.target.dataset.status) {
            let status = parseInt(event.target.dataset.status);
            console.log("drop: %o %o", taskId, status);
            props.moveTask(taskId, status);
        }
    }

    function getTasks(lane) {
        console.log("getTasks: %o", lane);
        return Object.values(props.tasks)
            .filter(task => task.status === lane.status)
            .map(task => (
                <Card className="task" border="secondary" data-id={task.id} onDragStart={dragStart} onDragEnd={dragEnd} draggable="true">
                    <Card.Header>
                        <Card.Title>{task.title}
                            <Button className="pull-right edit" variant="outline-secondary" onClick={edit.bind(this, task)}><FontAwesomeIcon icon="pencil-alt" size="sm" /></Button>
                        </Card.Title>
                    </Card.Header>
                    <Card.Body>
                        {task.description}
                    </Card.Body>
                </Card>
            ));
    }


    console.log("Lanes: %o", props.lanes)
    let lanes = props.lanes.map((lane, index) => {
        return (
            <div className="col-md-4 col-xs-12">
                <Card key={lane.id}>
                    <Card.Header>
                        {lane.title} {index === 0 ? (
                            <Button variant="primary"
                                size="sm"
                                className="pull-right"
                                onClick={addTask}>
                                <FontAwesomeIcon icon="plus" /></Button>) : null}
                    </Card.Header>
                    <Card.Body>{lane.description}</Card.Body>
                </Card>
                <div className="drop" data-status={lane.status} onDrop={drop} onDragOver={dragOver}>{getTasks(lane)}</div>
            </div>
        )
    });
    return (
        <div>
            <Row>{lanes}</Row>
        </div>
    );
}

export default Lanes;

// src/components/Lanes.vue
<template>
  <div class="row">
    <div v-for="lane in lanes" :key="lane.id" class="col-md-4 col-xs-12">
      <div class="card">
        <!-- Default panel contents -->
        <div class="card-header">
          <FontAwesomeIcon :icon="lane.icon" />
          {{ lane.title }}
        </div>
        <div class="card-body">
          <p>Tasks newly added in the backlog.</p>
        </div>
      </div>
      <div class="drop" :data-status="lane.status" @dragover="dragOver" @drop="drop">
        <ul class="list-group task">
          <li
            v-for="task in Object.values(tasks).filter(
              (task) => task.status === lane.status
            )"
            :key="task.id"
            :data-id="task.id"
            class="list-group-item"
            draggable="true"
            @dragstart="dragStart"
            @dragend="dragEnd"
          >
            <h4>
              {{ task.title }}
              <button
                type="button"
                class="btn btn-sm btn-primary pull-right"
                @click="edit(task)"
              >
                <span><FontAwesomeIcon icon="pencil-alt" /></span>
              </button>
            </h4>
            <p>{{ task.description }}</p>
          </li>
        </ul>
      </div>
    </div>
    <div v-if="editTask">
      <EditTask :task="editTask" @update:task="updateTask"></EditTask>
    </div>
  </div>
</template>

<script>
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faCheckCircle,
  faList,
  faHourglassStart,
  faPencilAlt,
  faUser,
} from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";
import EditTask from "./EditTask.vue";

let icons = [faList, faCheckCircle, faHourglassStart, faPencilAlt, faUser];
icons.forEach((icon) => library.add(icon));

export default {
  name: "ToDos",
  data() {
    return {
      editTask: null,
    };
  },
  props: {
    lanes: Array,
    tasks: Object,
  },
  methods: {
    nextState(task) {
      task.status++;
      //let tasks = { ...this.tasks };
      this.$emit("update:tasks", this.tasks);
    },
    edit(task) {
      console.log(task);
      this.editTask = task;
    },
    updateTask(task) {
      this.editTask = null;
      let tasks = { ...this.tasks, [task.id]: task };
      console.log(tasks);
      this.$emit("update:tasks", tasks);
    },
    dragStart(event) {
      event.dataTransfer.dropEffect = "move";
      event.dataTransfer.setData("text/plain", event.target.dataset.id);
      event.currentTarget.classList.add("drag");
      console.log(event);
      let taskId = event.dataTransfer.getData("text/plain");
      console.log("Drop: taskId=%s", taskId);
    },
    dragEnd(event) {
      event.currentTarget.classList.remove("drag");
      console.log("DrageEnd: %o", event);
    },
    dragOver(event) {
      event.preventDefault();
      event.dataTransfer.dropEffect = "move";
      let taskId = event.dataTransfer.getData("text/plain");
      console.log("Drop: taskId=%s", taskId);
    },
    drop(event) {
      event.preventDefault();
      let taskId = event.dataTransfer.getData("text/plain");
      console.log("Drop: taskId=%s", taskId);
      let task = this.tasks[taskId];
      let status = parseInt(event.target.dataset.status);
      console.log("Drop: status=%s, task=%o", status, task);
      task.status = status;
      this.$emit("update:tasks", this.tasks);
    },
  },
  components: {
    FontAwesomeIcon,
    EditTask,
  },
};
</script>

<style>
.pull-right {
  float: right;
  padding: 1px;
}

.task {
  margin-top: 5px;
}

.drop {
  position: relative;
  height: 100%;
}

.drag {
  opacity: 0.5;
}
</style>
